version: '3'

volumes:
  database:

services:
  db:
    image: postgres
    restart: always
    container_name: docker_postgres
    env_file: .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  server:
    container_name: docker_node
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 8080
      NODE_ENV: development
    command: npm run dev
    restart: always
    depends_on:
      - "db"

